'''
Nanopore DNA-Seq workflow
Copyright (C) 2024, Pedro Garrido Rodríguez
'''

include: 'rules/align.smk'
# include: 'rules/diploid.smk'
# include: 'rules/hapdiff.smk'
include: 'rules/marginphase.smk'
include: 'rules/modkit.smk'
include: 'rules/pepper.smk'
include: 'rules/sniffles2.smk'
include: 'rules/vntrs_hg38.smk'

SAMPLES = glob_wildcards(config['input']+'/{sample}.bam').sample

rule all:
    input:
        expand(config['outdir']+'/VCF/{sample}.vcf.gz.tbi', sample=SAMPLES),
        expand(config['outdir']+'/modkit/{sample}.bed', sample=SAMPLES),
        expand(config['outdir']+'/sniffles2/{sample}.vcf.gz.tbi', sample=SAMPLES)
