'''
Nanopore RDA-Seq workflow
Copyright (C) 2024, Pedro Garrido Rodríguez
'''

include: 'rules/diploid.smk'
include: 'rules/hapdiff.smk'
include: 'rules/marginphase.smk'
include: 'rules/pepper.smk'

SAMPLES = glob_wildcards(config['input']+'/uBAM/{sample}.bam').sample

rule all:
    input:
        expand(config['outdir']+'/VCF/{sample}.vcf.gz.tbi', sample=SAMPLES)
